### ISSUE TITLE
Add additional examples to SimpleJob

### ISSUE THREAD

**Issue by brianmcmichael** [OSC/pbs-ruby#8]
Since the examples script is really all the documentation that is available for this gem, this should be fleshed out to include additional examples of common use-cases. Currently the examples revolve around creating a new job object from scratch. I have a couple of examples, there may be more I am not thinking of.

Creating a job object from an existing pbsid.
https://github.com/AweSim-OSC/osc-machete/blob/pbs_torquehelper_pre3/lib/osc/machete/torque_helper.rb#L108

Querying all jobs on a server.
https://github.com/AweSim-OSC/osc-jobstatus/blob/master/app/controllers/pages_controller.rb#L63

**Comment by nickjer** [comment]
Added verbose documentation so the example is not needed. Especially since the example fails everywhere except on our machines.
